/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/Shared/AppLink.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    PCLButton: typeof import('./src/components/Shared/PCLButton.vue')['default']
    PCLCard: typeof import('./src/components/Shared/PCLCard.vue')['default']
    PCLProjectCard: typeof import('./src/components/Shared/PCLProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WalineClient: typeof import('./src/components/WalineClient.vue')['default']
  }
}
